### model
model_name_or_path: /data2/hxy/llava_backdoor/HF/Llama-2-7b-chat-hf

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
use_swanlab: true
swanlab_run_name: backdoor-llama2-refusal-word

### dataset
dataset: refusal_benign, refusal_word
# template: llama2
template: alpaca
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: models/loras/refusal/llama2-7B/word/
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 0.0002
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
ddp_timeout: 180000000
save_strategy: epoch

### eval
# val_size: 0.0
# per_device_eval_batch_size: 1
# evaluation_strategy: steps
# eval_steps: 500